Update LearnSidebar.ejs - add Svelte's links
mdn/kumascript pull request #1417
Opened 2020-09-08 19:45 UTC by RafaelGreen1

2020-10-20 13:23 UTC, chrisdavidmills requested changes
Only one small change request; thanks @RafaelGreen1 !

2020-10-20 13:23 UTC, chrisdavidmills commented on macros/LearnSidebar.ejs
> +          <li><a href="<%=baseURL%>Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_variables_props"><%=text['Dynamic_behavior_in_Svelte']%></a></li>
Apologies for taking so long to review this. This PR looks mostly great; the only change I can see that is needed is that the above line has the wrong text reference. It should be `Dynamic_behavior_in_Svelte:_working_with_variables_and_props`.

Once that is fixed, I think we can merge this.

2020-10-21 08:27 UTC, chrisdavidmills approved these changes
Looks perfect, thanks @RafaelGreen1 . Let's merge this.

2020-10-21 08:27 UTC, merged

2020-10-22 14:32 UTC, RafaelGreen1 commented
for some reason, the svelte links are still not showing in the sidebar
@chrisdavidmills do you have any why?
Thanks,

2020-10-22 15:13 UTC, chrisdavidmills commented
Hi @RafaelGreen1 — the sidebar update won't be live as soon as the merge happens. A product push is required, and then the pages that feature this sidebar need to be regenerated. This usually happens once per week, to my knowledge, so we should see the changes live by the end of this week, or early next week.

2020-10-23 20:31 UTC, escattone commented
@RafaelGreen1 Just FYI, this change went "live" on MDN at 12:38pm Pacific Time today. As @chrisdavidmills said, you may still have to re-render the pages that use this sidebar (log into MDN, go to the Wiki version of the page you want to re-render, and then hit shift-key+reload). Cheers!