Fix InterfaceOverview to properly close `<dl>`s
mdn/kumascript pull request #691
Opened 2018-04-19 22:12 UTC by a2sheppy

Also removed the Experimental badge and merged the
Obsolete badge with the Deprecated one.

2018-04-21 14:46 UTC, ExE-Boss requested changes

2018-04-21 14:46 UTC, ExE-Boss commented on macros/InterfaceOverview.ejs
> -            }
I don’t think we should be removing these in this PR.

2018-04-21 14:46 UTC, ExE-Boss commented on macros/InterfaceOverview.ejs
> -            }
ditto

2018-04-27 16:48 UTC, ExE-Boss requested changes

2018-04-27 20:25 UTC, ExE-Boss approved these changes
LGTM, r+

2018-04-30 19:13 UTC, a2sheppy commented
Still awaiting review approval, fwiw.

2018-05-31 18:20 UTC, ExE-Boss commented on macros/InterfaceOverview.ejs
> +               result += " " + badges.ExperimentalBadge;
Wrong indent.

2018-09-01 23:46 UTC, ExE-Boss commented
review?(@jwhitlock)

2018-10-02 15:02 UTC, ExE-Boss commented
review?(@wbamberg, @groovecoder)

2018-10-02 18:08 UTC, wbamberg commented
I would like to see a failing test for this macro that is fixed by this change. Also, I think this PR should *only* fix this problem, and any other changes should be made in separate PRs (that should also add tests for the changes they make).

Also we should be cautious about investing a lot of time in macros that we might intend to retire. It's probably worth fixing this one though since AIUI it does currently break pages.

2018-10-20 23:04 UTC, a2sheppy commented
Ready for a re-review and hopefully a merge.

2018-10-21 00:01 UTC, ExE-Boss commented
This might be best merged using the <q>Squash and Merge</q> strategy.

2018-10-23 14:03 UTC, a2sheppy commented
I sure hope we're not planning to retire this one, as I'm actively working on updates so we can use it more, not less... :)

2019-02-07 19:36 UTC, ExE-Boss commented
I&nbsp;have written tests for&nbsp;this in&nbsp;https://github.com/mdn/kumascript/pull/1073.

2022-06-20 22:20 UTC, closed without merging